New version of project
Glajik/diet-routine pull request #16
Opened 2020-08-15 10:17 UTC by valyuscha

Create the mane structure of the project + set up Redux + set up React-Router

2020-08-28 13:20 UTC, Glajik requested changes
I left some comments and questions. I decided to apply this pull request later, directly to the Development branch. There are a lot of deletions here. They are best done after applying `feature/firestore` branch.

2020-08-28 13:20 UTC, Glajik commented on database.rules.json
> -  /* Visit https://firebase.google.com/docs/database/security to learn more about security rules. */
Ну вот за что ты удалила комментарий))

2020-08-28 13:20 UTC, Glajik commented on database.rules.json
> +    ".write": "auth != null"
Согласен, так более правильно.

2020-08-28 13:20 UTC, Glajik commented on firebase.json
> +    "source": "functions"
Что это?

2020-08-28 13:20 UTC, Glajik commented on storage.rules
> -rules_version = '2';
Случайно удалила?

2020-08-28 13:20 UTC, Glajik commented on web-client/README.md
> -This project was bootstrapped with [Create React App](https://github.com/facebook/create-react-app), using the [Redux](https://redux.js.org/) and [Redux Toolkit](https://redux-toolkit.js.org/) templa
Я решил не удалять README.md — пусть останется для справки пока. Особенно ссылки из раздела ## Learn More

2020-08-28 13:20 UTC, Glajik commented on web-client/public/index.html
> -    <link rel="icon" href="%PUBLIC_URL%/favicon.ico" />
Я оставил %PUBLIC_URL%

2020-08-28 13:20 UTC, Glajik commented on web-client/public/index.html
> -    -->
Так же сохранил этот комментарий

2020-08-28 13:20 UTC, Glajik commented on web-client/public/robots.txt
> -User-agent: *
Зачем удалила? Этот файл нужен для настроек индексации.

2020-08-28 13:20 UTC, Glajik commented on web-client/src/index.js
> -serviceWorker.unregister();
Это потом пригодится

2020-08-28 13:20 UTC, Glajik commented on web-client/src/index.js
> -import * as serviceWorker from './serviceWorker';
Файл `serviceWorker.js` не нужно было удалять

2020-08-28 13:20 UTC, Glajik commented on web-client/src/index.js
> -import store from './app/store';
Конфигурировать `store` в отдельном файле на самом деле хорошая идея

2020-08-28 13:20 UTC, Glajik commented on web-client/src/serviceWorker.js
> -// opt-in, read https://bit.ly/CRA-PWA
Это не лишний файл) Тут надо почитать зачем он нужен - все написано.

2020-08-28 13:20 UTC, Glajik commented on web-client/src/setupTests.js
> -import '@testing-library/jest-dom/extend-expect';
Оставлю. Тесты будут.

2020-08-28 13:20 UTC, Glajik commented on web-client/src/components/App/App.js
> +export default App
Не уверен, стоит ли корневому компоненту приложения жить в `components/`

2020-08-29 10:27 UTC, merged

2020-08-29 10:33 UTC, Glajik commented
Ugh! It was hardcore!!! But I managed to merge the histories.

2020-08-31 13:59 UTC, valyuscha commented on web-client/src/components/App/App.js
> +export default App
Корень нашего приложения - index.js. App.js - компонент в котором собраны все компоненты приложения. Соответственно, он может быть в папке (components). (по крайней мере, во всех источниках меня учили App.js ставить в папку components)